<?php
require_once '/velox/php/core.php';
require_once '/velox/php/config.php';

use KitsuneTech\Velox;

// Generic template for Velox query definition - replace placeholder info as appropriate
// -------------------------------------------------------------------------------------

/*
$QUERY_VERSION should be incremented any time the result set schema changes. This will be sent as a header with the response
and allows the client-side service worker (if it exists) to update the schema of the corresponding IndexedDB instance. Per
the IndexedDB spec, version numbers must be positive integers. Normal semantic versioning doesn't apply here.
(If this variable doesn't exist or is set to 0, no IndexedDB will be generated by the service worker and the results
 will not be cached.)
*/

$QUERY_VERSION = 1;

//$conn should be either set with the appropriate values here, or better yet, should be assigned as a pre-existing connection.
$conn = $GLOBALS['VeloxConnections']['my-db-name'];
$conn = new Velox\Connection("server","database", "user", "password");

/*
$queries should be adjusted to correspond to the correct queries to populate and manipulate the data in the model. Additional
custom queries can be defined in this array and called by attaching the query name as a property to the request object, having
the appropriate 'where' and 'values' criteria as necessary.

Example: to call $QUERIES['myCustomQuery'], the request object would include something like 
  myCustomQuery: {where: [{field1: ["=","something"]}], values: {field1: "something else", field2: "another value"}

The query keys specified in this template ("SELECT","UPDATE","INSERT","DELETE") have specific meaning to the implementation
of this library. Specifically, $QUERIES['SELECT'] defines the data set, and the associated Query or PreparedStatement for
$QUERIES['UPDATE'], $QUERIES['INSERT'], or $QUERIES['DELETE'] should be written in such a way as to have the equivalent effect
on that data set. If any one of these query types is not intended to be used on the data set, it may be omitted. Each of the
latter three queries, when called, is followed by a new call to $QUERIES['SELECT'] to retrieve the updated result set. If
$QUERIES['SELECT'] is not defined, no Model is generated, and any results generated by a custom query are returned directly
as a JSON-formatted array of objects in name-value pair format.
*/
$QUERIES = [
    'SELECT' => new Velox\PreparedStatement($conn, "SELECT * FROM myTable WHERE myColumn = :myData"),
    'UPDATE' => new Velox\PreparedStatement($conn, "UPDATE myTable SET myColumn = :myData WHERE anotherColumn = :myCondition"),
    'INSERT' => new Velox\PreparedStatement($conn, "INSERT INTO myTable (myColumn) VALUES (:myData)"),
    'DELETE' => new Velox\PreparedStatement($conn, "DELETE FROM myTable WHERE myColumn = :myData")
];

function postProcessing($model){
    //If any post-processing needs to be done after the model is generated but before the results are output,
    //do it here. The Model instance for this query will be assigned to the $model argument, and this function
    //will be run after the instance is generated and synchronized. This function can be omitted if no post-processing
    //is needed.
}